
import AppPackage.AnimationClass;
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manish
 */
public class Buypage extends javax.swing.JFrame {
AnimationClass AC = new AnimationClass();     
    /**
     * Creates new form Buypage
     */
    public Buypage(String item,String email) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        try
{Class.forName("com.mysql.jdbc.Driver");
 Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root","");
 Statement st=conn.createStatement();
 String str1="Select * from data where itemno='"+item+"';";
ResultSet rs=st.executeQuery(str1);
if(rs.next())
{srno=rs.getInt("srno");
    title=rs.getString("title");
plot=rs.getString("plot");
release=rs.getString("rel");
price=rs.getInt("price");
rate=rs.getDouble("rating");
dur=rs.getInt("duration");


}
   ImageIcon a = new ImageIcon(getClass().getResource("photos/"+item+"i.png"));
ImageIcon b = new ImageIcon(getClass().getResource("photos/"+item+"p.png"));   

   if(srno<45)
{
du.setVisible(false);
jLabel11.setVisible(false);}
ti.setText(" "+title);
pl.setText(plot);
pr.setText(price+"");
du.setText(dur+" mins");
ra.setText(rate+"/10");
re.setText(release);
//
ico.setIcon(a);  
pre.setIcon(b);
jLabel14.setText(title);
jLabel12.setText(price+"");
}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}

        try
{Class.forName("com.mysql.jdbc.Driver");
 Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
 Statement st=conn.createStatement();
String str2="select acno,fname from accounts where email=\""+email+"\"";
ResultSet rs=st.executeQuery(str2);
if(rs.next())
{cartno=rs.getInt("acno");
cartname=rs.getString("fname");}}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}
    }
 
    
   public void added()
    {
        new Thread()
        {
            
        @Override
        public void run()
        {
        try{
            
         jLabel1.setText("Added item to cart");
         Thread.sleep(400);
jLabel1.setText("");        }
        catch(Exception e)
        {
        }
        
        }
        }.start();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mini2 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cartadd = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pre = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pl = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        ra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        re = new javax.swing.JLabel();
        du = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(488, 570));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(488, 570));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        mini2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mini2.setForeground(new java.awt.Color(154, 15, 187));
        mini2.setText("_");
        mini2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini2MouseExited(evt);
            }
        });
        getContentPane().add(mini2);
        mini2.setBounds(450, 7, 9, 17);

        exit2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(154, 15, 187));
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2MouseExited(evt);
            }
        });
        getContentPane().add(exit2);
        exit2.setBounds(470, 6, 10, 17);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heroex.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 488, 30);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(488, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(488, 540));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 216, 62));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 495, 100, 20));

        cartadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cart.png"))); // NOI18N
        cartadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartaddMouseExited(evt);
            }
        });
        jPanel2.add(cartadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 575, 120, 30));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rs.");
        jLabel15.setOpaque(true);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 20, 20));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amazing Spider Man");
        jLabel14.setOpaque(true);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 170, 20));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("1000");
        jLabel12.setOpaque(true);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 60, 20));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addcart.png"))); // NOI18N
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 488, 130));

        pre.setText("jLabel1");
        pre.setOpaque(true);
        jPanel2.add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 488, 200));
        pre.getAccessibleContext().setAccessibleDescription("");

        ti.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 40)); // NOI18N
        ti.setForeground(new java.awt.Color(255, 255, 255));
        ti.setText(" The Dark Knight (2011)");
        jPanel2.add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 488, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, 468, 1));
        jPanel2.add(ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 267, 90, 130));

        jScrollPane1.setBorder(null);

        pl.setEditable(false);
        pl.setBackground(new java.awt.Color(0, 0, 0));
        pl.setColumns(20);
        pl.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        pl.setForeground(new java.awt.Color(255, 255, 255));
        pl.setLineWrap(true);
        pl.setRows(5);
        pl.setText("When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham, the Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.");
        pl.setWrapStyleWord(true);
        pl.setBorder(null);
        jScrollPane1.setViewportView(pl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 267, 348, 130));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 412, 468, 1));

        ra.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        ra.setForeground(new java.awt.Color(255, 255, 255));
        ra.setText("9.8/10");
        jPanel2.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rs.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 420, 30, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rate.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 420, 60, 30));

        pr.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        pr.setForeground(new java.awt.Color(255, 255, 255));
        pr.setText("3000");
        jPanel2.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 420, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Release Date:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 450, 140, 30));

        re.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        re.setForeground(new java.awt.Color(255, 255, 255));
        re.setText("15 October 2009");
        jPanel2.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 450, 180, 30));

        du.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        du.setForeground(new java.awt.Color(255, 255, 255));
        du.setText("128 mins");
        jPanel2.add(du, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 420, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 420, 30, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOpaque(true);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 468, 1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 30, 488, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 String title,plot,release,cartname;
 int dur,price,cartno,srno;
 double rate;
 
    private void cartaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaddMouseEntered
ImageIcon i = new ImageIcon(getClass().getResource("cart1.png"));
cartadd.setIcon(i);
// TODO add your handling code here:
    }//GEN-LAST:event_cartaddMouseEntered

    private void cartaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaddMouseExited
ImageIcon i = new ImageIcon(getClass().getResource("cart.png"));
cartadd.setIcon(i);  
// TODO add your handling code here:
    }//GEN-LAST:event_cartaddMouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
AC.jLabelYUp(520, 410, 10, 10, jLabel16);
AC.jLabelYUp(580, 470, 10, 10, jLabel12);
AC.jLabelYUp(580, 470, 10, 10, jLabel14);
AC.jLabelYUp(580, 470, 10, 10, jLabel15);
AC.jLabelYUp(575, 465, 10, 10, cartadd);  
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
    
        
        
      
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
AC.jLabelYDown(410, 520, 10, 10, jLabel16);
AC.jLabelYDown(470, 580, 10, 10, jLabel12);
AC.jLabelYDown(470, 580, 10, 10, jLabel14);
AC.jLabelYDown(470, 580, 10, 10, jLabel15);
AC.jLabelYDown(465, 575, 10, 10, cartadd);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseClicked

    private void exit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseEntered
        exit2.setForeground(new Color(199,2,2));        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseEntered

    private void exit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseExited
        exit2.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseExited

    private void mini2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MouseClicked
        this.setState(SignUp.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_mini2MouseClicked

    private void mini2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MouseEntered
        mini2.setForeground(new Color(25,20,209));          // TODO add your handling code here:
    }//GEN-LAST:event_mini2MouseEntered

    private void mini2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MouseExited
        mini2.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_mini2MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cartaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaddMouseClicked
try
{Class.forName("com.mysql.jdbc.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
Statement st=conn.createStatement();
 srno=0;
String str="Select max(srno)s from "+cartno+cartname+";";
ResultSet rs=st.executeQuery(str);
if(rs.next())
srno=rs.getInt("s")+1;
else
srno=1;
}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}  
        try
{Class.forName("com.mysql.jdbc.Driver");
 Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
 Statement st=conn.createStatement();
String str3="insert into "+cartno+cartname+" values("+srno+",\""+ti.getText()+"\","+Integer.parseInt(pr.getText())+")";
st.executeUpdate(str3);
added();

}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}// TODO add your handling code here:
    }//GEN-LAST:event_cartaddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buypage("batmanc1","gandhidarshm@gmail.com").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartadd;
    private javax.swing.JLabel du;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel ico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mini2;
    private javax.swing.JTextArea pl;
    private javax.swing.JLabel pr;
    private javax.swing.JLabel pre;
    private javax.swing.JLabel ra;
    private javax.swing.JLabel re;
    private javax.swing.JLabel ti;
    // End of variables declaration//GEN-END:variables
}
