
import java.awt.Color;
import java.sql.*;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manish
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    public Cart(String email,String firstc) {
      initComponents();
           this.setLocationRelativeTo(null);
           jDialog1.setLocationRelativeTo(null);
           jDialog1.setBackground(new Color(0,0,0,0));
           Empty.setVisible(false);
           l2.setVisible(false);
           s2.setVisible(false);
           Card.setVisible(false);
           Wrong.setVisible(false);
           exit1.setVisible(false);
           Wrong1.setVisible(false);
           jLabel11.setVisible(false);
           firstname=firstc;
           mail=email;
           Conf.setEnabled(false);
           try
{Class.forName("com.mysql.jdbc.Driver");
 Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
 Statement st=conn.createStatement();
String str2="select acno,address,mobile from accounts where email=\""+email+"\"";
ResultSet rs=st.executeQuery(str2);
if(rs.next())
{cartno=rs.getInt("acno");
address=rs.getString("address");
adr.setText(address);
 phoneno=rs.getLong("mobile");

}}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}
DefaultTableModel nr=(DefaultTableModel)ta1.getModel();
nr.setRowCount(0);
try
{Class.forName("com.mysql.jdbc.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
Statement st=conn.createStatement();
String str="Select * from "+cartno+firstc+";";
ResultSet rs=st.executeQuery(str);
while(rs.next())
{int srno=rs.getInt("srno");
String prod=rs.getString("product");
int price=rs.getInt("price");
nr.addRow(new Object[]{srno,prod,price});}
if(ta1.getRowCount()==0)
    Empty.setVisible(true);
rs.close();
st.close();
conn.close();}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());} 
try
{Class.forName("com.mysql.jdbc.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
Statement st=conn.createStatement();
String str="Select sum(price)p from "+cartno+firstc+";";
ResultSet rs=st.executeQuery(str);
if(rs.next())
{ sum=rs.getInt("p");
total.setText(sum+"");}
rs.close();
st.close();
conn.close();}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}
    
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        Wrong1 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Enter = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Wrong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        s3 = new javax.swing.JSeparator();
        o2 = new javax.swing.JTextField();
        s4 = new javax.swing.JSeparator();
        o3 = new javax.swing.JTextField();
        s5 = new javax.swing.JSeparator();
        o4 = new javax.swing.JTextField();
        s1 = new javax.swing.JSeparator();
        o1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        home2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        s2 = new javax.swing.JSeparator();
        Card = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        Empty = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        r3 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        adr = new javax.swing.JTextArea();
        Conf = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        mini3 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(387, 372));
        jDialog1.setUndecorated(true);
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Wrong1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Wrong1.setForeground(new java.awt.Color(255, 255, 255));
        Wrong1.setText("Your Order will reach its destination within 10-15 business days.");
        jDialog1.getContentPane().add(Wrong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 230, 360, 20));

        exit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(154, 15, 187));
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit1MouseExited(evt);
            }
        });
        jDialog1.getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 10, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 245, 123));
        jLabel11.setText("Transaction Completed !!!");
        jLabel11.setOpaque(true);
        jDialog1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 370, 330));

        Enter.setForeground(new java.awt.Color(254, 252, 255));
        Enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enter.png"))); // NOI18N
        Enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnterMouseExited(evt);
            }
        });
        jDialog1.getContentPane().add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 290, 60, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter the OTP");
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 80, 90, 20));

        Wrong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Wrong.setForeground(new java.awt.Color(235, 1, 1));
        Wrong.setText("You Have Entered the Wrong OTP. Try Again");
        jDialog1.getContentPane().add(Wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 230, 260, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A 4-digit OTP has been sent to your mobile phone through SMS. ");
        jDialog1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 360, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Did not receive the OTP ?");
        jDialog1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 190, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("One Last Step");
        jDialog1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 20));

        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setToolTipText("");
        s3.setName(""); // NOI18N
        s3.setOpaque(true);
        jDialog1.getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 141, 20, 1));

        o2.setBackground(new java.awt.Color(0, 0, 0));
        o2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        o2.setForeground(new java.awt.Color(255, 255, 255));
        o2.setText(" ");
        o2.setBorder(null);
        o2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o2ActionPerformed(evt);
            }
        });
        o2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                o2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                o2FocusLost(evt);
            }
        });
        o2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o2KeyTyped(evt);
            }
        });
        jDialog1.getContentPane().add(o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 20, 20));

        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setToolTipText("");
        s4.setName(""); // NOI18N
        s4.setOpaque(true);
        jDialog1.getContentPane().add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 141, 20, 1));

        o3.setBackground(new java.awt.Color(0, 0, 0));
        o3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        o3.setForeground(new java.awt.Color(255, 255, 255));
        o3.setText(" ");
        o3.setBorder(null);
        o3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o3ActionPerformed(evt);
            }
        });
        o3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                o3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                o3FocusLost(evt);
            }
        });
        o3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o3KeyTyped(evt);
            }
        });
        jDialog1.getContentPane().add(o3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 20, 20));

        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setToolTipText("");
        s5.setName(""); // NOI18N
        s5.setOpaque(true);
        jDialog1.getContentPane().add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 141, 20, 1));

        o4.setBackground(new java.awt.Color(0, 0, 0));
        o4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        o4.setForeground(new java.awt.Color(255, 255, 255));
        o4.setText(" ");
        o4.setBorder(null);
        o4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o4ActionPerformed(evt);
            }
        });
        o4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                o4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                o4FocusLost(evt);
            }
        });
        o4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o4KeyTyped(evt);
            }
        });
        jDialog1.getContentPane().add(o4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 20, 20));

        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setToolTipText("");
        s1.setName(""); // NOI18N
        s1.setOpaque(true);
        jDialog1.getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 141, 20, 1));

        o1.setBackground(new java.awt.Color(0, 0, 0));
        o1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        o1.setForeground(new java.awt.Color(255, 255, 255));
        o1.setText(" ");
        o1.setBorder(null);
        o1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o1MouseClicked(evt);
            }
        });
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });
        o1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                o1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                o1FocusLost(evt);
            }
        });
        o1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                o1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o1KeyTyped(evt);
            }
        });
        jDialog1.getContentPane().add(o1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 20, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Resend");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jDialog1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 193, 50, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otp.png"))); // NOI18N
        jDialog1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 387, 372));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter the OTP to Confirm your Order");
        jDialog1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home2.setForeground(new java.awt.Color(255, 255, 255));
        home2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home2.setText("Your Cart");
        home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home2MouseExited(evt);
            }
        });
        getContentPane().add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 0, 210, 20));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l3.setForeground(new java.awt.Color(254, 252, 255));
        l3.setText("Address");
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 280, 50, 20));

        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setToolTipText("");
        s2.setName(""); // NOI18N
        s2.setOpaque(true);
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 246, 210, 1));

        Card.setBackground(new java.awt.Color(0, 0, 0));
        Card.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Card.setForeground(new java.awt.Color(255, 255, 255));
        Card.setBorder(null);
        Card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardActionPerformed(evt);
            }
        });
        Card.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CardFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CardFocusLost(evt);
            }
        });
        jPanel1.add(Card, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 225, 210, 20));

        l2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l2.setForeground(new java.awt.Color(254, 252, 255));
        l2.setText("Credit Card Number");
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 205, 110, 20));

        Empty.setBackground(new java.awt.Color(0, 0, 0));
        Empty.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Empty.setForeground(new java.awt.Color(154, 15, 187));
        Empty.setText("                                          Your Shopping Cart is Empty ");
        Empty.setOpaque(true);
        jPanel1.add(Empty, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, 640, 99));

        jScrollPane1.setBorder(null);

        ta1.setBackground(new java.awt.Color(0, 0, 0));
        ta1.setForeground(new java.awt.Color(255, 255, 255));
        ta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Product", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ta1.setGridColor(new java.awt.Color(0, 0, 0));
        ta1.setSelectionBackground(new java.awt.Color(154, 15, 187));
        ta1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(ta1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 640, 120));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 640, 1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 640, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rs");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 153, 30, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("0");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 153, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Net Total :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 153, 100, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 15, 187), 1, true), "Payment Method", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 10), new java.awt.Color(154, 15, 187))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r3.setBackground(new java.awt.Color(0, 0, 0));
        bg.add(r3);
        r3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("Debit Card");
        r3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/not.png"))); // NOI18N
        r3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        r3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        r3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/radio.png"))); // NOI18N
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel2.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 20, -1, 20));

        r1.setBackground(new java.awt.Color(0, 0, 0));
        bg.add(r1);
        r1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("Cash on Delivery");
        r1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/not.png"))); // NOI18N
        r1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        r1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        r1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/radio.png"))); // NOI18N
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        r1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1FocusLost(evt);
            }
        });
        jPanel2.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        r2.setBackground(new java.awt.Color(0, 0, 0));
        bg.add(r2);
        r2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("Credit Card");
        r2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/not.png"))); // NOI18N
        r2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        r2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        r2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/radio.png"))); // NOI18N
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel2.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 200, 320, 50));

        jScrollPane2.setBorder(null);

        adr.setBackground(new java.awt.Color(0, 0, 0));
        adr.setColumns(20);
        adr.setForeground(new java.awt.Color(255, 255, 255));
        adr.setRows(5);
        adr.setText(" ");
        adr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        adr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adrMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(adr);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 260, 100));

        Conf.setBackground(new java.awt.Color(0, 0, 0));
        Conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Confirm.png"))); // NOI18N
        Conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfMouseExited(evt);
            }
        });
        jPanel1.add(Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 664, 410));

        exit3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit3.setForeground(new java.awt.Color(154, 15, 187));
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit3MouseExited(evt);
            }
        });
        getContentPane().add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 10, -1));

        mini3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mini3.setForeground(new java.awt.Color(154, 15, 187));
        mini3.setText("_");
        mini3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini3MouseExited(evt);
            }
        });
        getContentPane().add(mini3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        home1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home1.setForeground(new java.awt.Color(255, 255, 255));
        home1.setText("< Home");
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
        });
        getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel61.setBackground(new java.awt.Color(0, 0, 0));
        jLabel61.setOpaque(true);
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 664, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String firstname,mail,address,otp,random;
int cartno,sum;
long phoneno;
    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
DefaultTableModel nr=(DefaultTableModel)ta1.getModel();
if(r3.isSelected()==true)
{r3.setForeground(new Color(154,15,187));
r1.setForeground(new Color(255,255,255));
r2.setForeground(new Color(255,255,255));
l2.setText("Debit Card Number");
l2.setVisible(true);
s2.setVisible(true);
Card.setVisible(true);
if(ta1.getRowCount()!=0)
Conf.setEnabled(true);}
else 
{r3.setForeground(new Color(255,255,255));}        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
DefaultTableModel nr=(DefaultTableModel)ta1.getModel();
if(r1.isSelected()==true)
{r1.setForeground(new Color(154,15,187));
r2.setForeground(new Color(255,255,255));
r3.setForeground(new Color(255,255,255));
l2.setVisible(false);
s2.setVisible(false);
Card.setVisible(false);
if(ta1.getRowCount()!=0)
Conf.setEnabled(true);}
else
{r1.setForeground(new Color(255,255,255));}// TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
DefaultTableModel nr=(DefaultTableModel)ta1.getModel();
if(r2.isSelected()==true)
{r2.setForeground(new Color(154,15,187));
r1.setForeground(new Color(255,255,255));
r3.setForeground(new Color(255,255,255));
l2.setText("Credit Card Number");
l2.setVisible(true);
s2.setVisible(true);
Card.setVisible(true);
if(ta1.getRowCount()!=0)
Conf.setEnabled(true);}
else
{r2.setForeground(new Color(255,255,255));}        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void CardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardActionPerformed

    private void CardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CardFocusGained
        Card.setForeground(new Color(154,15,187));
        l2.setForeground(new Color(154,15,187));
        s2.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_CardFocusGained

    private void CardFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CardFocusLost
        Card.setForeground(new Color(255,255,255));
        l2.setForeground(new Color(255,255,255));
        s2.setBackground(new Color(255,255,255));           // TODO add your handling code here:
    }//GEN-LAST:event_CardFocusLost

    private void adrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adrMouseEntered

// TODO add your handling code here:
    }//GEN-LAST:event_adrMouseEntered

    private void adrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adrMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_adrMouseExited

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exit3MouseClicked

    private void exit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseEntered
        exit3.setForeground(new Color(199,2,2));        // TODO add your handling code here:
    }//GEN-LAST:event_exit3MouseEntered

    private void exit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseExited
        exit3.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_exit3MouseExited

    private void mini3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseClicked
        this.setState(SignUp.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_mini3MouseClicked

    private void mini3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseEntered
        mini3.setForeground(new Color(25,20,209));          // TODO add your handling code here:
    }//GEN-LAST:event_mini3MouseEntered

    private void mini3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseExited
        mini3.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_mini3MouseExited

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
        home1.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
        home1.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_home1MouseExited

    private void home2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_home2MouseEntered

    private void home2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_home2MouseExited

    private void ConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfMouseEntered
ImageIcon i = new ImageIcon(getClass().getResource("Confirm1.png"));
Conf.setIcon(i);         // TODO add your handling code here:
    }//GEN-LAST:event_ConfMouseEntered

    private void ConfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfMouseExited
ImageIcon i = new ImageIcon(getClass().getResource("Confirm.png"));
Conf.setIcon(i);         // TODO add your handling code here:
    }//GEN-LAST:event_ConfMouseExited

    private void r1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_r1FocusLost

    private void ConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfMouseClicked
jDialog1.setVisible(true);   
this.setVisible(false);
try
{Class.forName("com.mysql.jdbc.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
Statement st=conn.createStatement();
String str="Update accounts set address=\""+adr.getText()+"\" where acno="+cartno+";";
st.executeUpdate(str);

}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());} 
smsotp o=new smsotp();
o.sendSms(phoneno,random,firstname,sum);
// TODO add your handling code here:
    }//GEN-LAST:event_ConfMouseClicked

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o1ActionPerformed

    private void o1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o1FocusGained
        o1.setForeground(new Color(154,15,187));
        s1.setBackground(new Color(154,15,187));             // TODO add your handling code here:
    }//GEN-LAST:event_o1FocusGained

    private void o1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o1FocusLost
        o1.setForeground(new Color(255,255,255));
        s1.setBackground(new Color(255,255,255));             // TODO add your handling code here:
    }//GEN-LAST:event_o1FocusLost

    private void o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o2ActionPerformed

    private void o2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o2FocusGained
o2.setForeground(new Color(154,15,187));
        s3.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_o2FocusGained

    private void o2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o2FocusLost
      o2.setForeground(new Color(255,255,255));
        s3.setBackground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_o2FocusLost

    private void o3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o3ActionPerformed

    private void o3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o3FocusGained
o3.setForeground(new Color(154,15,187));
        s4.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_o3FocusGained

    private void o3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o3FocusLost
      o3.setForeground(new Color(255,255,255));
        s4.setBackground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_o3FocusLost

    private void o4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o4ActionPerformed

    private void o4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o4FocusGained
o4.setForeground(new Color(154,15,187));
        s5.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_o4FocusGained

    private void o4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_o4FocusLost
       o4.setForeground(new Color(255,255,255));
        s5.setBackground(new Color(255,255,255));       // TODO add your handling code here:
    }//GEN-LAST:event_o4FocusLost

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
jLabel8.setForeground(new Color(154,15,187));         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
jLabel8.setForeground(new Color(255,255,225));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterMouseClicked
String a=o1.getText().trim()+o2.getText().trim()+o3.getText().trim()+o4.getText().trim();
if(random.equals(a))
{       try
{Class.forName("com.mysql.jdbc.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
Statement st=conn.createStatement();
String str="Delete from "+cartno+firstname+";";
st.executeUpdate(str);

}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}
             exit1.setVisible(true);
           jLabel11.setVisible(true); 
            Wrong1.setVisible(true);}
else
   Wrong.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_EnterMouseClicked

    private void EnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("enter1.png"));
        Enter.setIcon(i);// TODO add your handling code here:
    }//GEN-LAST:event_EnterMouseEntered

    private void EnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("enter.png"));
        Enter.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_EnterMouseExited

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
Homepage h=new Homepage(mail);
this.dispose();
h.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseClicked

    private void exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseEntered
        exit1.setForeground(new Color(199,2,2));        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseEntered

    private void exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseExited
        exit1.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseExited

    private void o1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o1MouseClicked

    private void o1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_o1KeyPressed

    private void o1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o1KeyTyped
o2.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_o1KeyTyped

    private void o2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o2KeyTyped
o3.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_o2KeyTyped

    private void o3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o3KeyTyped
o4.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_o3KeyTyped

    private void o4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o4KeyTyped
Enter.requestFocus();  // TODO add your handling code here:
    }//GEN-LAST:event_o4KeyTyped

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
Homepage h=new Homepage(mail);
this.dispose();
h.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_home1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
home2.setText(firstname+"'s Cart"); 
try
{otp="123456789";
Random rd=new Random();
StringBuilder sb=new StringBuilder(4);
for(int i=0;i<4;i++)
    sb.append(otp.charAt(rd.nextInt(otp.length())));
random=sb.toString();
}
catch(Exception d)
{JOptionPane.showMessageDialog(null, d.getMessage());}  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
smsotp o=new smsotp();
o.sendSms(phoneno,random,firstname,sum);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart("gandhidarshm@gmail.com","Darsh").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Card;
    private javax.swing.JLabel Conf;
    private javax.swing.JLabel Empty;
    private javax.swing.JLabel Enter;
    private javax.swing.JLabel Wrong;
    private javax.swing.JLabel Wrong1;
    private javax.swing.JTextArea adr;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel home1;
    private javax.swing.JLabel home2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel mini3;
    private javax.swing.JTextField o1;
    private javax.swing.JTextField o2;
    private javax.swing.JTextField o3;
    private javax.swing.JTextField o4;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JSeparator s1;
    private javax.swing.JSeparator s2;
    private javax.swing.JSeparator s3;
    private javax.swing.JSeparator s4;
    private javax.swing.JSeparator s5;
    private javax.swing.JTable ta1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
