
import AppPackage.AnimationClass;
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manish
 */
public class MarvelDC extends javax.swing.JFrame {
    AnimationClass AC = new AnimationClass();


    /**
     * Creates new form MarvelDC
     */
    public MarvelDC() {
        initComponents();
        this.setLocationRelativeTo(null);
        slideshow1();
        slideshow();
        al1.requestFocusInWindow();
    }
     

    public void slideshow()
    {
        new Thread()
        {
            int count;
        @Override
        public void run()
        {ImageIcon a = new ImageIcon(getClass().getResource("ani1.png"));
         ImageIcon b = new ImageIcon(getClass().getResource("ani2.png"));
         ImageIcon c = new ImageIcon(getClass().getResource("ani3.png")); 
         ImageIcon d = new ImageIcon(getClass().getResource("ani4.png"));
        try{
            
          while(true)
          {
              switch(count)
          {      
                  case 0:al1.setIcon(a);
                  
                      Thread.sleep(6000);
                      al2.setIcon(b);
                         AC.jLabelXLeft(0, -700, 10, 7, al1);
                         AC.jLabelXLeft(700, 0, 10, 7, al2); 
                         count=1;
                         break;
                  case 1:
                       Thread.sleep(6000);
                      al1.setIcon(c);
                      AC.jLabelXRight(-700, 0, 10, 7, al1);
                         AC.jLabelXRight(0, 700, 10, 7, al2); 
                         count=2;
                         break;
                  case 2:
                      Thread.sleep(6000);
                      al2.setIcon(d);
                         AC.jLabelXLeft(0, -700, 10, 7, al1);
                         AC.jLabelXLeft(700, 0, 10, 7, al2); 
                         count=3;
                         break;     
                  case 3:
                      Thread.sleep(6000);
                      al1.setIcon(a);
                         AC.jLabelXRight(-700, 0, 10, 7, al1);
                         AC.jLabelXRight(0, 700, 10, 7, al2); 
                         count=0;
                         break; 
              }
          }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        }
        }.start();
    }
    public void slideshow1()
    {
        new Thread()
        {
            int count1;
        @Override
        public void run()
        {
        try{
            
          while(true)
          {
              switch(count1)
          {      
                  case 0:an1.setText("WELCOME TO MARVEL VS DC");
                 Thread.sleep(6000);
                  an2.setText("SIGN UP FOR FREE");
                       AC.jLabelXRight(0, 700, 10, 7, an1);
                         AC.jLabelXRight(-700, 0, 10, 7, an2); 
                         count1=1;
                         break;
                  case 1:
                       Thread.sleep(6000);
                      an1.setText("THE COMPLETE DATABASE OF MOVIES AND COMIC BOOKS");
                      AC.jLabelXLeft(700, 0, 10, 7, an1);
                         AC.jLabelXLeft(0, -700, 10, 7, an2); 
                         count1=2;
                         break;
                  case 2:
                      Thread.sleep(6000);
                      an2.setText("AT GREAT DEALS!!!");
                         AC.jLabelXRight(0, 700, 10, 7, an1);
                         AC.jLabelXRight(-700, 0, 10, 7, an2);
                         count1=3;
                         break;     
                  case 3:
                      Thread.sleep(6000);
                      an1.setText("WELCOME TO MARVEL VS DC");
                      AC.jLabelXLeft(700, 0, 10, 7, an1);
                         AC.jLabelXLeft(0, -700, 10, 7, an2);   
                         count1=0;
                         break; 
              }
          }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        passlog = new javax.swing.JPasswordField();
        pshow = new javax.swing.JTextField();
        LogButton = new javax.swing.JLabel();
        Signformbutton = new javax.swing.JLabel();
        s1 = new javax.swing.JSeparator();
        s2 = new javax.swing.JSeparator();
        l2 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        mini1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        logemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        an1 = new javax.swing.JLabel();
        an2 = new javax.swing.JLabel();
        al1 = new javax.swing.JLabel();
        al2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1022, 404));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l1.setForeground(new java.awt.Color(254, 252, 255));
        l1.setText("Email ID");
        jPanel2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 79, 60, 20));

        passlog.setBackground(new java.awt.Color(0, 0, 0));
        passlog.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        passlog.setForeground(new java.awt.Color(255, 255, 255));
        passlog.setBorder(null);
        passlog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passlogFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passlogFocusLost(evt);
            }
        });
        jPanel2.add(passlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 170, 200, 20));

        pshow.setBackground(new java.awt.Color(0, 0, 0));
        pshow.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pshow.setForeground(new java.awt.Color(255, 255, 255));
        pshow.setBorder(null);
        pshow.setFocusable(false);
        pshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pshowActionPerformed(evt);
            }
        });
        pshow.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pshowFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pshowFocusLost(evt);
            }
        });
        jPanel2.add(pshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 170, 200, 20));

        LogButton.setForeground(new java.awt.Color(254, 252, 255));
        LogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        LogButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogButtonMouseExited(evt);
            }
        });
        jPanel2.add(LogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 30));

        Signformbutton.setForeground(new java.awt.Color(154, 15, 187));
        Signformbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Register.png"))); // NOI18N
        Signformbutton.setText("Not a member yet ? Register");
        Signformbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignformbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignformbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignformbuttonMouseExited(evt);
            }
        });
        jPanel2.add(Signformbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 300, 200, 30));

        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setToolTipText("");
        s1.setName(""); // NOI18N
        s1.setOpaque(true);
        jPanel2.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 121, 200, 1));

        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setToolTipText("");
        s2.setName(""); // NOI18N
        s2.setOpaque(true);
        jPanel2.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 191, 200, 1));

        l2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l2.setForeground(new java.awt.Color(254, 252, 255));
        l2.setText("Password");
        jPanel2.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, 20));

        exit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(154, 15, 187));
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit1MouseExited(evt);
            }
        });
        jPanel2.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 10, -1));

        mini1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mini1.setForeground(new java.awt.Color(154, 15, 187));
        mini1.setText("_");
        mini1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini1MouseExited(evt);
            }
        });
        jPanel2.add(mini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 10, 17));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.setBorder(null);
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/not.png"))); // NOI18N
        jCheckBox1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/notick.png"))); // NOI18N
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jCheckBox1.setVerifyInputWhenFocusTarget(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 207, 120, -1));

        logemail.setBackground(new java.awt.Color(0, 0, 0));
        logemail.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        logemail.setForeground(new java.awt.Color(255, 255, 255));
        logemail.setBorder(null);
        logemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logemailActionPerformed(evt);
            }
        });
        logemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                logemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                logemailFocusLost(evt);
            }
        });
        jPanel2.add(logemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 100, 200, 20));

        jLabel2.setForeground(new java.awt.Color(199, 2, 2));
        jLabel2.setText(" ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 227, 210, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(700, 0, 322, 404);

        an1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 40)); // NOI18N
        an1.setForeground(new java.awt.Color(255, 255, 255));
        an1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(an1);
        an1.setBounds(0, 300, 700, 100);

        an2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 40)); // NOI18N
        an2.setForeground(new java.awt.Color(255, 255, 255));
        an2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(an2);
        an2.setBounds(-700, 300, 700, 100);
        getContentPane().add(al1);
        al1.setBounds(0, 0, 700, 404);
        getContentPane().add(al2);
        al2.setBounds(700, 0, 700, 404);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
String lemail,lpass,luserpass;
    private void SignformbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignformbuttonMouseClicked
        SignUp si= new SignUp();
        si.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_SignformbuttonMouseClicked

    private void LogButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogButtonMouseClicked
luserpass=new String(passlog.getPassword());
if(jCheckBox1.isSelected()==true)
luserpass=pshow.getText();
lemail=logemail.getText();
Homepage h= new Homepage(lemail);
        try
{Class.forName("com.mysql.jdbc.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
Statement st=conn.createStatement();
String str1="Select password from accounts where email='"+lemail+"';";
System.out.print(str1);
ResultSet rs=st.executeQuery(str1);
if(rs.next())
{lpass=rs.getString("password");
if (lpass.equals(luserpass))
{h.setVisible(true);
this.dispose();}
else
jLabel2.setText("Wrong Email ID or Password");}
}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());} 
        // TODO add your handling code here:
    }//GEN-LAST:event_LogButtonMouseClicked

    private void pshowFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pshowFocusLost
        pshow.setForeground(new Color(255,255,255));
        l2.setForeground(new Color(255,255,255));
        s2.setBackground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_pshowFocusLost

    private void pshowFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pshowFocusGained
        pshow.setForeground(new Color(154,15,187));
        l2.setForeground(new Color(154,15,187));
        s2.setBackground(new Color(154,15,187));
        // TODO add your handling code here:
    }//GEN-LAST:event_pshowFocusGained

    private void pshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pshowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pshowActionPerformed

    private void passlogFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passlogFocusLost
 passlog.setForeground(new Color(255,255,255));
        l2.setForeground(new Color(255,255,255));
        s2.setBackground(new Color(255,255,255));          // TODO add your handling code here:
    }//GEN-LAST:event_passlogFocusLost

    private void passlogFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passlogFocusGained
passlog.setForeground(new Color(154,15,187));
        l2.setForeground(new Color(154,15,187));
        s2.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_passlogFocusGained

    private void LogButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogButtonMouseEntered
ImageIcon i = new ImageIcon(getClass().getResource("login1.png"));
LogButton.setIcon(i);// TODO add your handling code here:
    }//GEN-LAST:event_LogButtonMouseEntered

    private void LogButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogButtonMouseExited
ImageIcon i = new ImageIcon(getClass().getResource("login.png"));
LogButton.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_LogButtonMouseExited

    private void SignformbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignformbuttonMouseEntered
ImageIcon i = new ImageIcon(getClass().getResource("Register1.png"));
Signformbutton.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_SignformbuttonMouseEntered

    private void SignformbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignformbuttonMouseExited
ImageIcon i = new ImageIcon(getClass().getResource("Register.png"));
Signformbutton.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_SignformbuttonMouseExited

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseClicked

    private void exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseEntered
exit1.setForeground(new Color(199,2,2));        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseEntered

    private void exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseExited
exit1.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseExited

    private void mini1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini1MouseClicked
this.setState(MarvelDC.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_mini1MouseClicked

    private void mini1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini1MouseEntered
mini1.setForeground(new Color(25,20,209));          // TODO add your handling code here:
    }//GEN-LAST:event_mini1MouseEntered

    private void mini1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini1MouseExited
mini1.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_mini1MouseExited

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
String a= new String(passlog.getPassword());
if(jCheckBox1.isSelected()==true)
{jCheckBox1.setForeground(new Color(154,15,187));
passlog.setVisible(false);
pshow.setFocusable(true);
pshow.setVisible(true);
pshow.setText(a);}
else
{jCheckBox1.setForeground(new Color(255,255,255));
passlog.setVisible(true);
passlog.setText(pshow.getText());
pshow.setVisible(false);
pshow.setFocusable(false);}// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void logemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logemailActionPerformed

    private void logemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logemailFocusGained
logemail.setForeground(new Color(154,15,187));
        l1.setForeground(new Color(154,15,187));
        s1.setBackground(new Color(154,15,187));             // TODO add your handling code here:
    }//GEN-LAST:event_logemailFocusGained

    private void logemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logemailFocusLost
logemail.setForeground(new Color(255,255,255));
        l1.setForeground(new Color(255,255,255));
        s1.setBackground(new Color(255,255,255));             // TODO add your handling code here:
    }//GEN-LAST:event_logemailFocusLost

    /**[154,15,187]
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarvelDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarvelDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarvelDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarvelDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarvelDC().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogButton;
    private javax.swing.JLabel Signformbutton;
    private javax.swing.JLabel al1;
    private javax.swing.JLabel al2;
    private javax.swing.JLabel an1;
    private javax.swing.JLabel an2;
    private javax.swing.JLabel exit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField logemail;
    private javax.swing.JLabel mini1;
    private javax.swing.JPasswordField passlog;
    private javax.swing.JTextField pshow;
    private javax.swing.JSeparator s1;
    private javax.swing.JSeparator s2;
    // End of variables declaration//GEN-END:variables
}
