
import java.awt.Color;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manish
 */
public class SignUp extends javax.swing.JFrame {
java.util.Date date;
java.sql.Date sqldate ;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        jDialog1.setLocationRelativeTo(null);
        jLabel4.requestFocusInWindow();
                     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        exit1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mini2 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        s1 = new javax.swing.JSeparator();
        first = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        s2 = new javax.swing.JSeparator();
        last = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        s3 = new javax.swing.JSeparator();
        emailid = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        Signbutton = new javax.swing.JLabel();
        s7 = new javax.swing.JSeparator();
        mobile1 = new javax.swing.JTextField();
        s4 = new javax.swing.JSeparator();
        mobile = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        s5 = new javax.swing.JSeparator();
        l10 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        s6 = new javax.swing.JSeparator();
        l6 = new javax.swing.JLabel();
        conpass1 = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JPasswordField();
        l5 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        cap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        birth = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(594, 218));
        jDialog1.setUndecorated(true);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(594, 218));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(154, 15, 187));
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit1MouseExited(evt);
            }
        });
        jPanel2.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 10, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 245, 123));
        jLabel11.setText("You have been successfully registered!!!");
        jLabel11.setOpaque(true);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, 590, 170));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 594, 218));

        jDialog1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 594, 218));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mini2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mini2.setForeground(new java.awt.Color(154, 15, 187));
        mini2.setText("_");
        mini2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini2MouseExited(evt);
            }
        });
        getContentPane().add(mini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 10, 17));

        exit2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(154, 15, 187));
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2MouseExited(evt);
            }
        });
        getContentPane().add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setToolTipText("");
        s1.setName(""); // NOI18N
        s1.setOpaque(true);
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 72, 162, 1));

        first.setBackground(new java.awt.Color(0, 0, 0));
        first.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        first.setForeground(new java.awt.Color(255, 255, 255));
        first.setBorder(null);
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        first.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstFocusLost(evt);
            }
        });
        jPanel1.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 51, 162, 20));

        l1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l1.setForeground(new java.awt.Color(254, 252, 255));
        l1.setText("First Name");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 20));

        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setToolTipText("");
        s2.setName(""); // NOI18N
        s2.setOpaque(true);
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 72, 162, 1));

        last.setBackground(new java.awt.Color(0, 0, 0));
        last.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        last.setForeground(new java.awt.Color(255, 255, 255));
        last.setBorder(null);
        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });
        last.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastFocusLost(evt);
            }
        });
        jPanel1.add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 51, 162, 20));

        l2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l2.setForeground(new java.awt.Color(254, 252, 255));
        l2.setText("Last Name");
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 30, 80, 20));

        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setToolTipText("");
        s3.setName(""); // NOI18N
        s3.setOpaque(true);
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 132, 200, 1));

        emailid.setBackground(new java.awt.Color(0, 0, 0));
        emailid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        emailid.setForeground(new java.awt.Color(255, 255, 255));
        emailid.setBorder(null);
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });
        emailid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailidFocusLost(evt);
            }
        });
        jPanel1.add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 111, 200, 20));

        l3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l3.setForeground(new java.awt.Color(254, 252, 255));
        l3.setText("Email ID");
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 20));

        Signbutton.setForeground(new java.awt.Color(255, 255, 255));
        Signbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupbut.png"))); // NOI18N
        Signbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignbuttonMouseExited(evt);
            }
        });
        jPanel1.add(Signbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 60, 30));

        s7.setForeground(new java.awt.Color(255, 255, 255));
        s7.setToolTipText("");
        s7.setName(""); // NOI18N
        s7.setOpaque(true);
        jPanel1.add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 411, 134, 1));

        mobile1.setBackground(new java.awt.Color(0, 0, 0));
        mobile1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mobile1.setForeground(new java.awt.Color(255, 255, 255));
        mobile1.setBorder(null);
        mobile1.setVerifyInputWhenFocusTarget(false);
        mobile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile1ActionPerformed(evt);
            }
        });
        mobile1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobile1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobile1FocusLost(evt);
            }
        });
        jPanel1.add(mobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 390, 130, 20));

        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setToolTipText("");
        s4.setName(""); // NOI18N
        s4.setOpaque(true);
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 132, 134, 1));

        mobile.setBackground(new java.awt.Color(0, 0, 0));
        mobile.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mobile.setForeground(new java.awt.Color(255, 255, 255));
        mobile.setBorder(null);
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileFocusLost(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 111, 134, 20));

        l4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l4.setForeground(new java.awt.Color(254, 252, 255));
        l4.setText("Mobile No.");
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 80, 20));

        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setToolTipText("");
        s5.setName(""); // NOI18N
        s5.setOpaque(true);
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 192, 162, 1));

        l10.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setText("Type the text ");
        jPanel1.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 20));

        l8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l8.setForeground(new java.awt.Color(254, 252, 255));
        l8.setText("Favourite Superhero");
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 210, 110, 20));

        l9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l9.setForeground(new java.awt.Color(154, 15, 187));
        l9.setText("reCAPTCHA");
        jPanel1.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 20));

        l7.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l7.setForeground(new java.awt.Color(254, 252, 255));
        l7.setText("Date of Birth");
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 20));

        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setToolTipText("");
        s6.setName(""); // NOI18N
        s6.setOpaque(true);
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 192, 162, 1));

        l6.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l6.setForeground(new java.awt.Color(254, 252, 255));
        l6.setText("Confirm Password");
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 150, 110, 20));

        conpass1.setBackground(new java.awt.Color(0, 0, 0));
        conpass1.setForeground(new java.awt.Color(255, 255, 255));
        conpass1.setBorder(null);
        conpass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conpass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                conpass1FocusLost(evt);
            }
        });
        jPanel1.add(conpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 171, 162, 20));

        pass1.setBackground(new java.awt.Color(0, 0, 0));
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        pass1.setBorder(null);
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass1FocusLost(evt);
            }
        });
        jPanel1.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 171, 162, 20));

        l5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        l5.setForeground(new java.awt.Color(254, 252, 255));
        l5.setText("Password");
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 20));

        c1.setBackground(new java.awt.Color(154, 15, 187));
        c1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Batman", "Iron Man", "Superman", "Spiderman", "Wonder Woman", "Captain America", " " }));
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 231, 162, -1));

        jSeparator2.setBackground(new java.awt.Color(39, 22, 205));
        jSeparator2.setForeground(new java.awt.Color(39, 22, 205));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 300, 238, 1));

        jSeparator1.setBackground(new java.awt.Color(222, 2, 16));
        jSeparator1.setForeground(new java.awt.Color(222, 2, 16));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 340, 238, 1));

        cap.setEditable(false);
        cap.setBackground(new java.awt.Color(0, 0, 0));
        cap.setFont(new java.awt.Font("Chiller", 1, 92)); // NOI18N
        cap.setForeground(new java.awt.Color(154, 15, 187));
        cap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 15, 187), 1, true));
        cap.setFocusable(false);
        jPanel1.add(cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 240, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retryc.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 310, 20, 20));

        birth.setBackground(new java.awt.Color(0, 0, 0));
        birth.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel1.add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 231, 162, -1));

        jLabel5.setForeground(new java.awt.Color(199, 2, 2));
        jLabel5.setText(" ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 425, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 396, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 396, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/md.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 396, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String lname,email,pass,conpass,str,str1,captcha,random,userrandom;
public String fname;
int eno,i=0,a=0,b=0;
long mno;
Object hero;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{Class.forName("com.mysql.jdbc.Driver");
 Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
 Statement st=conn.createStatement();
 eno=0;
 str="Select max(acno)e from accounts;";
ResultSet rs=st.executeQuery(str);
if(rs.next())
eno=rs.getInt("e")+1;
else
eno=1;
}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}   
try
{captcha="qwert1y23456ui7op8a9sdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
Random rd=new Random();
StringBuilder sb=new StringBuilder(5);
for(int i=0;i<5;i++)
sb.append(captcha.charAt(rd.nextInt(captcha.length())));
random=sb.toString();
cap.setText(random);}
catch(Exception d)
{JOptionPane.showMessageDialog(null, d.getMessage());}// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstActionPerformed

    private void firstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstFocusGained
        first.setForeground(new Color(154,15,187));
        l1.setForeground(new Color(154,15,187));
        s1.setBackground(new Color(154,15,187));             // TODO add your handling code here:
    }//GEN-LAST:event_firstFocusGained

    private void firstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstFocusLost
        first.setForeground(new Color(255,255,255));
        l1.setForeground(new Color(255,255,255));
        s1.setBackground(new Color(255,255,255));             // TODO add your handling code here:
    }//GEN-LAST:event_firstFocusLost

    private void lastFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastFocusLost
  last.setForeground(new Color(255,255,255));
        l2.setForeground(new Color(255,255,255));
        s2.setBackground(new Color(255,255,255));           // TODO add your handling code here:
    }//GEN-LAST:event_lastFocusLost

    private void lastFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastFocusGained
last.setForeground(new Color(154,15,187));
l2.setForeground(new Color(154,15,187));
s2.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_lastFocusGained

    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastActionPerformed

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidActionPerformed

    private void emailidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailidFocusGained
emailid.setForeground(new Color(154,15,187));
l3.setForeground(new Color(154,15,187));
s3.setBackground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_emailidFocusGained

    private void emailidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailidFocusLost
  emailid.setForeground(new Color(255,255,255));
        l3.setForeground(new Color(255,255,255));
        s3.setBackground(new Color(255,255,255));           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_emailidFocusLost

    private void SignbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignbuttonMouseClicked
DefaultComboBoxModel dm=(DefaultComboBoxModel)c1.getModel();
hero=c1.getSelectedItem();
fname=first.getText();
lname=last.getText();
email=emailid.getText();
mno=Long.parseLong(mobile.getText());
pass=new String (pass1.getPassword());
conpass=new String (conpass1.getPassword());
date=birth.getDate();
sqldate=new java.sql.Date(date.getTime());
userrandom=mobile1.getText();
 try
{Class.forName("com.mysql.jdbc.Driver");
 Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
 str1="insert into accounts(acno,fname,lname,email,mobile,dob,superhero,password) values("+eno+",'"+fname+"','"+lname+"','"+email+"',"+mno+",'"+sqldate+"','"+hero+"','"+pass+"');";
 String str="Create table "+eno+fname+" (Srno int,Product varchar(60),Price double(8,2));";
 Statement st1=conn.createStatement();
 if(pass.equals(conpass))
{if(random.equals(userrandom))
{st1.executeUpdate(str1);
 st1.executeUpdate(str);
 jDialog1.setVisible(true);
 this.dispose();}
 else
{jLabel5.setText("Please enter the proper reCAPTCHA text.");
 try
{captcha="qwert1y23456ui7op8a9sdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
 Random rd=new Random();
 StringBuilder sb=new StringBuilder(5);
 for(int i=0;i<5;i++)
 sb.append(captcha.charAt(rd.nextInt(captcha.length())));
 random=sb.toString();
 cap.setText(random);}
 catch(Exception d)
{JOptionPane.showMessageDialog(null, d.getMessage());}}
}
 else
 jLabel5.setText("You have entered the wrong password.");
 }
 catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());}
     //    try
//{Class.forName("com.mysql.jdbc.Driver");
 //Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "");
 //Statement st=conn.createStatement();
 
//}
//catch(Exception e)
//{JOptionPane.showMessageDialog(null, e.getMessage());} 
        // TODO add your handling code here:
    }//GEN-LAST:event_SignbuttonMouseClicked

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusGained
mobile.setForeground(new Color(154,15,187));
l4.setForeground(new Color(154,15,187));
s4.setBackground(new Color(154,15,187));       // TODO add your handling code here:
    }//GEN-LAST:event_mobileFocusGained

    private void mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusLost
mobile.setForeground(new Color(255,255,255));
l4.setForeground(new Color(255,255,255));
s4.setBackground(new Color(255,255,255));       // TODO add your handling code here:
    }//GEN-LAST:event_mobileFocusLost

    private void conpass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conpass1FocusGained
conpass1.setForeground(new Color(154,15,187));
l6.setForeground(new Color(154,15,187));
s6.setBackground(new Color(154,15,187));         // TODO add your handling code here:
    }//GEN-LAST:event_conpass1FocusGained

    private void conpass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conpass1FocusLost
conpass1.setForeground(new Color(255,255,255));
l6.setForeground(new Color(255,255,255));
s6.setBackground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_conpass1FocusLost

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
pass1.setForeground(new Color(154,15,187));
l5.setForeground(new Color(154,15,187));
s5.setBackground(new Color(154,15,187));         // TODO add your handling code here:
    }//GEN-LAST:event_pass1FocusGained

    private void pass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusLost
pass1.setForeground(new Color(255,255,255));
l5.setForeground(new Color(255,255,255));
s5.setBackground(new Color(255,255,255));   
  // TODO add your handling code here:
    }//GEN-LAST:event_pass1FocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
try
{captcha="qwert1y23456ui7op8a9sdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
Random rd=new Random();
StringBuilder sb=new StringBuilder(5);
for(int i=0;i<5;i++)
    sb.append(captcha.charAt(rd.nextInt(captcha.length())));
random=sb.toString();
cap.setText(random);}
catch(Exception d)
{JOptionPane.showMessageDialog(null, d.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseClicked

    private void exit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseEntered
        exit2.setForeground(new Color(199,2,2));        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseEntered

    private void exit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseExited
        exit2.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseExited

    private void mini2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MouseClicked
        this.setState(SignUp.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_mini2MouseClicked

    private void mini2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MouseEntered
        mini2.setForeground(new Color(25,20,209));          // TODO add your handling code here:
    }//GEN-LAST:event_mini2MouseEntered

    private void mini2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini2MouseExited
        mini2.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_mini2MouseExited

    private void mobile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile1ActionPerformed

    private void mobile1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile1FocusGained
mobile1.setForeground(new Color(154,15,187));
l10.setForeground(new Color(154,15,187));
s7.setBackground(new Color(154,15,187));            // TODO add your handling code here:
    }//GEN-LAST:event_mobile1FocusGained

    private void mobile1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile1FocusLost
mobile1.setForeground(new Color(255,255,255));
l10.setForeground(new Color(255,255,255));
s7.setBackground(new Color(255,255,255));            // TODO add your handling code here:
    }//GEN-LAST:event_mobile1FocusLost

    private void SignbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignbuttonMouseEntered
ImageIcon i = new ImageIcon(getClass().getResource("signupbut1.png"));
Signbutton.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_SignbuttonMouseEntered

    private void SignbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignbuttonMouseExited
ImageIcon i = new ImageIcon(getClass().getResource("signupbut.png"));
Signbutton.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_SignbuttonMouseExited

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
jDialog1.dispose();
MarvelDC m=new MarvelDC();
m.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseClicked

    private void exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseEntered
        exit1.setForeground(new Color(199,2,2));        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseEntered

    private void exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseExited
        exit1.setForeground(new Color(154,15,187));        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Signbutton;
    private com.toedter.calendar.JDateChooser birth;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox c1;
    private javax.swing.JTextField cap;
    private javax.swing.JPasswordField conpass1;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JTextField first;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField last;
    private javax.swing.JLabel mini2;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField mobile1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JSeparator s1;
    private javax.swing.JSeparator s2;
    private javax.swing.JSeparator s3;
    private javax.swing.JSeparator s4;
    private javax.swing.JSeparator s5;
    private javax.swing.JSeparator s6;
    private javax.swing.JSeparator s7;
    // End of variables declaration//GEN-END:variables
}
